GRT Elephant Brain
randoop/randoop pull request #1347
Opened 2024-07-04 06:20 UTC by 776styjsu

Manage method sequences (to create inputs) in the SequenceCollection with the exact types obtained at run-time. This feature diversifies the input object types by using dynamic type information to find objects that cannot be generated using static type information alone.

2024-07-04 23:57 UTC, 776styjsu commented
Current implementation has some problems at the moment. Will be fixed soon.

2024-10-06 16:34 UTC, mernst requested changes

2024-10-06 16:34 UTC, mernst commented on src/main/java/randoop/generation/ForwardGenerator.java
> +      // Get the last variable in the sequence that has the expected type, cast it to the actual
Don't we know this is the first variable in the last statement in the sequence?  Is there a more straightforward way to get it than making a list of all the variables of the given type (which seems like unnecessary work)?

2025-04-28 18:37 UTC, RockingMat commented on src/main/java/randoop/generation/ForwardGenerator.java
> +    }
You can add a check for if lastValues.getObjectValue() is null here.

2025-04-28 18:43 UTC, RockingMat commented on src/main/java/randoop/generation/ForwardGenerator.java
> +    ReferenceValue lastValue = lastValues.get(0);
It may be worth handling multiple return values here.

2025-04-28 18:45 UTC, RockingMat commented on src/main/java/randoop/generation/ForwardGenerator.java
> +      TypedOperation castOperation = TypedOperation.createCast(declaredType, runTimeType);
The original paper only downcasts with a certain probability(50%)

2025-05-04 17:44 UTC, mernst requested changes

2025-05-04 17:44 UTC, mernst commented on src/main/java/randoop/generation/ForwardGenerator.java
> +      // Re-execute the sequence after applying dynamic type casting.
Please only re-execute the sequence if necessary -- that is, if `castToRunTimeType` *needed* to insert a cast because it changed the variable type.

2025-05-04 17:44 UTC, mernst commented on src/main/java/randoop/generation/ForwardGenerator.java
> +    List<ReferenceValue> lastValues = eSeq.getLastStatementValues();
I don't think we want to consider all the values of the last statement, but only the return value of the last call.  A side effect to an existing value cannot change the value's run-time class.

2025-05-04 17:44 UTC, mernst commented on src/main/java/randoop/generation/ForwardGenerator.java
> +    if (!runTimeType.equals(declaredType) && runTimeType.isSubtypeOf(declaredType)) {
Under what circumstance can `runTimeType.isSubtypeOf(declaredType)` be false?  If it should always be true, then please write it as an assertion rather than in the `if` condition.

2025-05-04 17:44 UTC, mernst commented on src/main/java/randoop/generation/ForwardGenerator.java
> +      Variable variable = eSeq.sequence.firstVariableForTypeLastStatement(declaredType, false);
As noted above, I think that Elephant Brain should only work on the return value of the method called.  So the logic in `firstVariableForTypeLastStatement` is not necessary.

2025-05-04 17:44 UTC, mernst commented on src/main/java/randoop/generation/ForwardGenerator.java
> +      if (variable != null) {
How can `variable` be null?  If it is null, does that indicate a bug in Elephant Brain?  If so, please make it an assertion rather than an `if` condition.

2025-05-04 17:44 UTC, mernst commented on src/main/java/randoop/sequence/Sequence.java
> +   * Return the first value of type {@code type} that is produced by, or might be side-effected by,
As noted elsewhere, I think the logic that is needed is to return the single value produced by the method call in the last statement (which should be to a non-void method).

2025-05-14 21:32 UTC, RockingMat commented on src/main/java/randoop/generation/ForwardGenerator.java
> +    List<ReferenceValue> lastValues = eSeq.getLastStatementValues();
Doesn't the code already do this by grabbing lastValues.get(0)?

2025-05-14 23:39 UTC, RockingMat commented
I have addressed the comments from the most recent code review @mernst. I don't understand how the matchesVariables method was created in this PR but is used in methods that weren't created in this PR such as allVariablesForTypeLastStatement.

2025-05-17 20:22 UTC, mernst requested changes
This looks great.   I have just two comments.

2025-05-17 20:22 UTC, mernst commented on src/main/java/randoop/generation/ForwardGenerator.java
> +      castToRunTimeType(eSeq);
Since this method may change its argument, I think it would be more appropriate as an instance method rather than a method defined outside `ExecutableSequence`.

Whether or not you do that, can some or all of the body of the `if` be folded into the routine, to make the call site cleaner and simpler?

2025-05-17 20:22 UTC, mernst commented on src/main/java/randoop/sequence/Sequence.java
> +  /**
This is a reasonable change, but could you make a separate PR for it?  (You don't have to remove it from this PR; that will happen automatically when the other one is merged and master is merged into this one.)

2025-05-27 00:05 UTC, mernst commented
I fixed several crashes; now the problem is coverage, which might indicate a deeper problem that @776styjsu needs to investigate.

2025-06-07 19:23 UTC, RockingMat commented
Thank you @mernst for simplifying the pull request and adding the nullness annotation. This pull request is no ready to be rereviewed.

2025-06-08 01:06 UTC, mernst commented on src/main/java/randoop/sequence/Sequence.java
> +   * // 'result' refers to 'num'
The comment says "Returns the first value of type {@code type} that is produced by, or might be side-effected by, the last statement."  However, the Integer `num` is neither produced by nor side-effected by `String text = num.toString();`.  So, either the comment (probably) or the example is wrong.  I think this method may return the first variable of the given type in the signature.

2025-06-08 03:38 UTC, RockingMat commented
I have fixed the comment. Thank you for the quick review @mernst!

2025-06-08 06:45 UTC, merged